name: Build on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest 
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Build
      shell: bash
      env: 
        CC: cl.exe
        CXX: cl.exe
      run: |
        mkdir build
        cd build
        cmake .. -GNinja
        cmake --build .
